version: '3.1'

services:
  mongodb: 
    image: mongo
    container_name: skill_matcher_mongodb
    restart: always
    ports:
      - '27017:27017'
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: skill-matcher
  localstack:
    image: localstack/localstack:latest
    container_name: skill_matcher_localstack
    ports:
      - '4563-4599:4563-4599'
      - '8055:8080'
    environment:
      - SERVICES=s3
      - DEBUG=1
      - EDGE_PORT=4566
      - DATA_DIR=/tmp/localstack/data
  api:
    build: ./api
    container_name: skill_matcher_api
    depends_on:
      - mongodb
    environment:
      - AWS_USE_LOCAL=true
      - AWS_REGION=ap-southeast-2
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - NODE_ENV=development
      - MONGO_URI=mongodb://root:password@mongodb:27017/skill-matcher
      - AWS_S3_PUBLIC_BUCKET_NAME=skill-matcher-bucket
      - AWS_S3_ENDPOINT=http://localstack:4566
    ports:
      - 8080:8080

  admin_client: 
    build: ./admin-client
    container_name: skill_matcher_admin_client
    depends_on:
      - api
    environment:
      - PUBLIC_API_BASE_URL=http://localhost:8080
    ports:
      - 8082:8082

   
  # user-client:
  #   build: ./user-client
  #   container_name: skill-matcher-user-client
  #   networks:
  #     - skill-matcher-net
  #   env_file:
  #     - ./user-client.env
  #   ports:
  #     - "8084:8081"



